In [73]:
import numpy as np

In [74]:
#python list
list_example = {1,"hello",2,3.5,4,5,True}

#Numpy Array
array_example = np.array([1,2,3,4,5],dtype=np.int32)

In [75]:
list_example

{1, 2, 3.5, 4, 5, 'hello'}

In [76]:
array_example

array([1, 2, 3, 4, 5], dtype=int32)

## Creating Arrays and Arrays Attributes

In [77]:
a=np.array([1,2,3])

In [78]:
print(type(a),"\n","shape:",a.shape,"\n","Indexed elements:",a[0],a[1],a[2])
a[0]= 5  # change an element of the array
print(a)

<class 'numpy.ndarray'> 
 shape: (3,) 
 Indexed elements: 1 2 3
[5 2 3]


In [79]:
type(a)

numpy.ndarray

In [80]:
b=np.array([[1,2],[3,4]])  # create a rank 2 array
print(b)

[[1 2]
 [3 4]]


In [81]:
print(b.shape)

(2, 2)


In [82]:
b.ndim

2

In [83]:
c= np.array([
    [[1,2],[3,4]],
    [[5,6],[6,7]]
])

In [84]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]]])

In [85]:
c.shape

(2, 2, 2)

##  Array Indexing and Slicing

In [86]:
# create the following rank 2 arrsy with shape [3,4]
# [1 2 3 4]
# [5 6 7 8]
#[9 10 11 12]
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# ise slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2;b is the following array of shape [2,2]:
#[2,3]
#[6,7]
b=a[0:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [87]:
# slice rows 0-2 and columns 1-2
c=a[0:3,1:3]
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## Array Initialiazation Methods

In [88]:
a=np.zeros((2,2),dtype=np.int32)  # cerate an array of all zeros
print(a)

[[0 0]
 [0 0]]


In [89]:
b=np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [90]:
c=np.eye(5,dtype=np.int32) #create a 2X2 indentity matrix
print(c)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## Array Arithmetic Operations

In [91]:
# addition
x=np.array([[1,2],[3,4]],dtype=np.int64)
y=np.array([[5,6],[7,8]],dtype=np.int64)

print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [92]:
# subtraction
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [93]:
# Multiplication
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [94]:
# Division
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [95]:
# dot product of vectors
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

v=np.array([9,10])
w=np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

219
219


## Argmax,Argmin,Argsort and Where 

## Aggregate Functions (min,max,sum)

In [96]:
# find indices of predictions above a confidence threshold
preds = np.array([0.2,0.5,0.93,0.9,0.1])
#predicted_class_index = np.argmax(preds)
#to_predict_class = ["apple","banana","ball","mango","orange"]


to_preict_class = ["apple","banana","ball","mango","orange"]
possible_class_indexes = np.where(preds > 0.85)[0]
print(possible_class_indexes)

[2 3]


In [97]:
a = np.array([1,8,9,-3,2,6,4])
# get the  index with maximum element in a 
print(np.argmax(a))

2


In [98]:
print(np.argmin(a))

3


In [99]:
print(np.argsort(a))

[3 0 4 6 5 1 2]


In [100]:
print(np.where(a>5)[0])

print(np.where(a>=[np.argmax(a)])[0])

[1 2 5]
[1 2 4 5 6]


## Determinant of a Matrix

In [101]:
x=np.array([[1,2],[3,4],[5,6]])

print(np.max(x)) # compute max of all elements: prints "6"
print(np.min(x)) # compute min of all elements: prints "1"
print(np.sum(x)) # compute sum of all elements: prints "21"

6
1
21


In [102]:
# create a 2D array to demonstrate axis-wise operations
x=np.array([[1,2,8],[5,3,1],[4,6,5]])
print(x)

print(np.max(x,axis=0))
print(np.max(x,axis=1))

[[1 2 8]
 [5 3 1]
 [4 6 5]]
[5 6 8]
[8 5 6]


In [103]:
# compute the determinant of matrix A
A = np.array([[1,2],[3,4]])

det_A = np.linalg.det(A)
print("Determinant:",det_A)

Determinant: -2.0000000000000004


## solving linear algebra 

In [104]:
# example system of linear equations:
# 2x + y = 5
# x - y = 1
A = np.array([[2,1],[1,-1]])
b= np.array([5,1])

solutions = np.linalg.solve(A,b)
print("solution",solutions)

solution [2. 1.]


In [105]:
# equation
# 3x+y-2z = 9
# 2x-y+z = 3
# x+2y+3z = 12

a = np.array([[3,1,-2],[2,-1,1],[1,2,3]])
b= np.array([9,3,12])
solutions = np.linalg.solve(a,b)
print("solution",solutions)

solution [2.6 3.2 1. ]


## Random Number Generation

In [106]:
# generate random numbers using numpy.random
random_number = np.random.rand()
print(random_number)

random_array_1d = np.random.rand(5)
print(random_array_1d)

random_array_2d = np.random.rand(3,3)
print(random_array_2d)

random_array_3d = np.random.rand(6,6,6)
print(random_array_3d)

0.08395425087038932
[0.40473892 0.08941905 0.78236664 0.20640126 0.17065659]
[[0.78579098 0.71527979 0.05938198]
 [0.03746648 0.4935321  0.15228828]
 [0.3418298  0.47686981 0.19357366]]
[[[0.45120488 0.17572268 0.99002547 0.21280989 0.4940819  0.74821276]
  [0.18592625 0.80850813 0.67921504 0.15686425 0.69506313 0.31856673]
  [0.86945307 0.48345479 0.79142402 0.45475534 0.20927826 0.31395084]
  [0.84745522 0.2578008  0.18503781 0.7590609  0.99590504 0.72645782]
  [0.69418377 0.88336067 0.51358594 0.26496061 0.32610923 0.74739745]
  [0.67061231 0.97001927 0.98658448 0.81169475 0.64804059 0.92426377]]

 [[0.12418624 0.00406332 0.96996623 0.41926533 0.97204289 0.63796634]
  [0.26433074 0.38077079 0.83127124 0.90254622 0.84444681 0.80844648]
  [0.250488   0.61356289 0.60671918 0.68408063 0.74829471 0.54968404]
  [0.14482726 0.6840055  0.03155237 0.03271898 0.00980349 0.92080796]
  [0.6002623  0.53218034 0.39180803 0.75993468 0.02809637 0.34134081]
  [0.3051985  0.33757954 0.75248538 0.9900

In [107]:
# generate random integers
random_int = np.random.randint(0,10)
print(random_int)
random_int_array = np.random.randint(0,10,size=5)
print(random_int_array)
random_int_array_2d = np.random.randint(0,20, size=(3,2))
print(random_int_array_2d)

0
[4 8 3 6 7]
[[ 9  0]
 [19  0]
 [ 0  0]]


In [108]:
# another example of generating random integer arrays
random_int_array = np.random.randint(0,10, size=5)
print(random_int_array)
random_int_array_2d = np.random.randint(0,20,size =(3,2))
print(random_int_array_2d)

[0 6 3 5 5]
[[ 1 14]
 [16 11]
 [ 8 14]]


In [109]:
# randomly sample elements from a list
random_sample = np.random.choice([1,2,34,5],size= 3)
print(random_sample)
random_sample_with_replacement = np.random.choice([1,2,3,4,5],size=3,replace =True)
print(random_sample_with_replacement)

[5 1 1]
[1 5 3]
